FROM buildpack-deps:{{ os_release }}-curl
# FROM {{ os_name }}:{{ os_release }}

# Set build-time argument for build version, with a default value
ARG IMAGE_BUILD_VERSION=v0.0.0
ENV IMAGE_BUILD_VERSION=${IMAGE_BUILD_VERSION}

ENV LANG C.UTF-8

{% if os_name in ['debian', 'ubuntu'] -%}
# Prevent interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive
{% endif %}

{% if os_default_python != python_version -%}
RUN <<RUN_CMD_EOF
apt-get update
apt-get install -y --no-install-recommends software-properties-common

add-apt-repository ppa:deadsnakes/ppa
apt update
apt install \
    python{{ python_version}} \
    python{{ python_version}}-dev

mkdir /tmp/python{{python_version}}-pip-install
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/python{{python_version}}-pip-install/get-pip.py
python{{python_version}} /tmp/python{{python_version}}-pip-install/get-pip.py
rm -fR /tmp/python{{python_version}}-pip-install

# Register the native Ubuntu python3 ({{ os_default_python }}) and the new python{{ python_version }}
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{ os_default_python }}) 1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{ python_version }} 2

# Force the system to use Python {{ python_version }} non-interactively
update-alternatives --set python3 /usr/bin/python{{ python_version }}
/usr/bin/python3 --version

# Clean up APT cache to reduce image size
rm -rf /var/lib/apt/lists/*
RUN_CMD_EOF
{%- endif %}

# Define image labels
LABEL org.opencontainers.image.title="organicveggie/docker-ansible" \
    org.opencontainers.image.description="Docker image for Ansible role testing with Python {{ python_version }} on {{ os_name | title }} {{ os_release | title }}" \
    org.opencontainers.image.version="${IMAGE_BUILD_VERSION}" \
    org.opencontainers.image.licenses="GPL-3.0-or-later" \
    org.opencontainers.image.source="https://github.com/organicveggie/docker-ansible"

CMD ["python{{ python_version }}"]