RUN <<RUN_CMD_EOF
# Remove useless Python environment warning flag.
rm -rf /usr/lib/python{{ os_default_python }}/EXTERNALLY-MANAGED

sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Fix potential UTF-8 errors with ansible-test.
locale-gen en_US.UTF-8
RUN_CMD_EOF

COPY images/initctl_faker .
RUN <<RUN_CMD_EOF
chmod +x initctl_faker
rm -fr /sbin/initctl
ln -s /initctl_faker /sbin/initctl
RUN_CMD_EOF

# Install Ansible inventory file.
RUN <<RUN_CMD_EOF
mkdir -p /etc/ansible
echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
RUN_CMD_EOF

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)
RUN <<RUN_CMD_EOF
rm -f /lib/systemd/system/systemd*udev*
rm -f /lib/systemd/system/getty.target
RUN_CMD_EOF

# Define image labels
LABEL org.opencontainers.image.authors="Sean Laurent" \
    org.opencontainers.image.base.name="buildpack-deps:{{ os_release }}-curl" \
    org.opencontainers.image.description="Docker image for Ansible role testing with Python {{ python_version }} on {{ os_name | title }} {{ os_release | title }}" \
    org.opencontainers.image.licenses="GPL-3.0-or-later" \
    org.opencontainers.image.source="https://github.com/organicveggie/docker-ansible" \
    org.opencontainers.image.title="organicveggie/docker-ansible" \
    org.opencontainers.image.version="${IMAGE_BUILD_VERSION}"

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]